[env:nucleo_l476rg]
platform = platformio/ststm32@20.0.0
platform_packages =
    platformio/toolchain-gccarmnoneeabi@1.120301.0
    platformio/framework-arduinoststm32@4.30000.0
board = nucleo_l476rg
framework = arduino
lib_deps = symlink://../..
